swagger: "2.0"
info:
  description: "These are the series of endpoints that make up the Hermes Cloud Backend"
  version: "0.0.1"
  title: "Hermes Cloud Backend"
  contact:
    email: "bjorn248@gmail.com"
  license:
    name: "GPLV3"
    url: "https://github.com/Bjorn248/Hermes-Cloud-Backend/blob/master/LICENSE"
host: "APIGATEWAY_URL"
basePath: "/dev"
tags:
- name: "register"
  description: "Register a user"
- name: "device"
  description: "Add and modify devices"
schemes:
- "https"
paths:
  /register:
    post:
      tags:
      - "register"
      summary: "Sign up for Hermes Cloud"
      description: ""
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Email and password for user registration"
        required: true
        schema:
          $ref: '#/definitions/UserCreationRequest'
      responses:
        200:
          description: "User created successfully"
          schema:
            $ref: '#/definitions/UserCreationResponse'
        409:
          description: "Conflict: User Exists"
          schema:
            $ref: '#/definitions/UserCreationResponseConflict'
  /device:
    post:
      tags:
      - "device"
      summary: "Device Management Endpoint"
      description: ""
      operationId: "addDevice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: header
        name: X-HERMES-CLOUD-TOKEN
        description: "Token to access this protected endpoint"
        required: true
        type: "string"
      - in: body
        name: "body"
        description: "Required info to register a device"
        required: true
        schema:
          $ref: '#/definitions/DeviceCreationRequest'
      responses:
        200:
          description: "Device created successfully"
          schema:
            $ref: '#/definitions/DeviceCreationResponse'
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/DeviceCreationResponseBadRequest'
        403:
          description: "Not Authorized"
          schema:
            $ref: '#/definitions/DeviceCreationResponseNoAuth'
        409:
          description: "Conflict"
          schema:
            $ref: '#/definitions/DeviceCreationResponseConflict'
    put:
      tags:
      - "device"
      summary: "Device Management Endpoint"
      description: ""
      operationId: "modifyDevice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: header
        name: X-HERMES-CLOUD-TOKEN
        description: "Token to access this protected endpoint"
        required: true
        type: "string"
      - in: body
        name: "body"
        description: "Required info to register a device"
        required: true
        schema:
          $ref: '#/definitions/DeviceModificationRequest'
      responses:
        204:
          description: "Device updated successfully"
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/DeviceModificationResponseBadRequest'
        403:
          description: "Forbidden"
          schema:
            $ref: '#/definitions/DeviceModificationResponseForbidden'
        500:
          description: "Error"
          schema:
            $ref: '#/definitions/DeviceModificationResponseError'
definitions:
  UserCreationRequest:
    type: "object"
    properties:
      email:
        type: "string"
        example: "example@example.com"
      password:
        type: "string"
        example: "HelloThere@1234"
  UserCreationResponse:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Successfully created user example@example.com"
      Error:
        type: "string"
        example: ""
  UserCreationResponseConflict:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Email is already registered: example@example.com"
      Error:
        type: "string"
        example: "User Creation Error"
  DeviceCreationRequest:
    type: "object"
    properties:
      mac:
        type: "string"
        example: "00:0a:95:9d:68:24"
      name:
        type: "string"
        example: "example-device-name"
      owner:
        type: "string"
        example: "example@example.com"
    required:
      - mac
      - name
      - owner
  DeviceCreationResponse:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Successfully registered device 00:0a:95:9d:68:24"
      Error:
        type: "string"
        example: ""
  DeviceCreationResponseConflict:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "The following MAC is already registered: 00:0a:95:9d:68:24"
      Error:
        type: "string"
        example: "Duplicate MAC Error"
  DeviceCreationResponseNoAuth:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Not authorized to perform this action"
      Error:
        type: "string"
        example: "Not authorized"
  DeviceCreationResponseBadRequest:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Error unmarshalling request body"
      Error:
        type: "string"
        example: "unexpected end of JSON input"
  DeviceModificationRequest:
    type: "object"
    properties:
      mac:
        type: "string"
      name:
        type: "string"
      status:
        type: "string"
    required:
      - mac
  DeviceModificationResponseError:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Error Updating Device"
      Error:
        type: "string"
        example: "Something went wrong"
  DeviceModificationResponseBadRequest:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Error unmarshalling request body"
      Error:
        type: "string"
        example: "unexpected end of JSON input"
  DeviceModificationResponseForbidden:
    type: "object"
    properties:
      Response:
        type: "string"
        example: "Not authorized to perform this action"
      Error:
        type: "string"
        example: "Not authorized"
externalDocs:
  description: "Contribute"
  url: "https://github.com/Bjorn248/Hermes-Cloud-Backend"
