swagger: "2.0"
info:
  description: "These are the series of endpoints that make up the Hermes Cloud Backend"
  version: "0.0.1"
  title: "Hermes Cloud Backend"
  contact:
    email: "bjorn248@gmail.com"
  license:
    name: "GPLV3"
    url: "https://github.com/Bjorn248/Hermes-Cloud-Backend/blob/master/LICENSE"
host: "APIGATEWAY_URL"
basePath: "/dev"
tags:
- name: "register"
  description: "Register a user"
- name: "device"
  description: "Add and modify devices"
schemes:
- "https"
paths:
  /register:
    post:
      tags:
      - "register"
      summary: "Sign up for Hermes Cloud"
      description: ""
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Email and password for user registration"
        required: true
        schema:
          $ref: '#/definitions/UserCreationRequest'
      responses:
        200:
          description: "User created successfully"
          schema:
            $ref: '#/definitions/UserAndDeviceCreationResponse'
        409:
          description: "Conflict: User Exists"
  /device:
    post:
      tags:
      - "device"
      summary: "Device Management Endpoint"
      description: ""
      operationId: "addDevice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: header
        name: X-HERMES-CLOUD-TOKEN
        description: "Token to access this protected endpoint"
        required: true
        type: "string"
      - in: body
        name: "body"
        description: "Required info to register a device"
        required: true
        schema:
          $ref: '#/definitions/DeviceRegistrationRequest'
      responses:
        200:
          description: "Device created successfully"
          schema:
            $ref: '#/definitions/UserAndDeviceCreationResponse'
    put:
      tags:
      - "device"
      summary: "Device Management Endpoint"
      description: ""
      operationId: "modifyDevice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: header
        name: X-HERMES-CLOUD-TOKEN
        description: "Token to access this protected endpoint"
        required: true
        type: "string"
      - in: body
        name: "body"
        description: "Required info to register a device"
        required: true
        schema:
          $ref: '#/definitions/DeviceModificationRequest'
      responses:
        200:
          description: "Device updated successfully"
          schema:
            $ref: '#/definitions/UserAndDeviceCreationResponse'
definitions:
  UserCreationRequest:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
  UserAndDeviceCreationResponse:
    type: "object"
    properties:
      Response:
        type: "string"
  DeviceRegistrationRequest:
    type: "object"
    properties:
      mac:
        type: "string"
      name:
        type: "string"
      owner:
        type: "string"
    required:
      - mac
      - name
      - owner
  DeviceModificationRequest:
    type: "object"
    properties:
      mac:
        type: "string"
      name:
        type: "string"
      status:
        type: "string"
    required:
      - mac
externalDocs:
  description: "Contribute"
  url: "https://github.com/Bjorn248/Hermes-Cloud-Backend"
